build:
	Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook', params=list('cache'=TRUE))"
	
build-no-cache:
	Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook', params=list('cache'=FALSE))"